### ISSUE TITLE
Fresh installation on register or login: 419 Page Expired

### ISSUE THREAD

**Issue by ballerburg9005** [pixelfed/support#106]
I have already checked the following issues, and nothing resolves it.

https://github.com/pixelfed/support/issues/37
https://github.com/pixelfed/pixelfed/issues/2192

Redis is running and verified working with Pixelfed. 

I first used .env.testing as template but then also tried all relevant combinations with .env.example (like changing session driver, switching to production). Setting any or all of APP_DOMAIN ADMIN_DOMAIN SESSION_DOMAIN either to blank or to localhost or to some /etc/hosts name pointing to eth0 IP address with IPv6 disabled changes nothing.

I ran php artisan config:clear && php artisan config:cache after changing the file.

At first I tunneled http through https with stunnel, but then I just removed URL::forceScheme('https').

I tried both php artisan serve as well as properly configured Apache with mod_rewrite enabled, no difference.

Permissions are correct of course and I used all the commands from the manual. There is also nothing weird in the php.ini, I even ran it with a clean one with just the extensions enabled and parameter set as described.

Other Laravel 7 and 8 projects work just fine.

**Comment by acdysknk** [comment]
Did you find a fix for this?
Thanks

**Comment by ballerburg9005** [comment]
No, and I tried really hard. My best bet is that it is either caused by my php version, or some weird little thing in my linux distribution (Archlinux). As it apparently seems to be working for other people, and it is literally the only things I didn't switch out with something else during testing.

**Comment by kgnfth** [comment]
every time you change .env or update Pixelfed you have to run these commands

```
php artisan config:cache
php artisan route:cache
php artisan view:cache
```

**Comment by ballerburg9005** [comment]
@kgnfth This is convered by the manual and doesn't change the issue.

**Comment by dallasgroot** [comment]
I had a 419 error yesterday after wiping my bone working instance and starting over. The cause of my 419 error was an issue with 
`APP_URL=http://localhost
APP_DOMAIN="localhost"
ADMIN_DOMAIN="localhost"
SESSION_DOMAIN="localhost" ` where both admin domain and session domain were both spelled with an extra charachtor for me. Once I corrected this section and re cached artisan I didn’t get that error anymore. Hope that helps

**Comment by aleighco** [comment]
I have seen this issue in my environment, and in my case, it was caused by the server bouncing from https:// to http:/ or https:// to http:/ so you might check if that is the behavior you are experiencing.

**Comment by ballerburg9005** [comment]
@aleighco:

It is best to remove URL::forceScheme('https') in app/Providers/AppServiceProvider.php and set 'secure' => false, in  config/session.php for testing.

**Comment by aleighco** [comment]
> @aleighco:
> 
> It is best to remove URL::forceScheme('https') for testing.

It's in production. What we did instead is prevent all access to http://

**Comment by ahangarha** [comment]
I am running PexelFed locally.

I have removed `URL::forceScheme('https')`, Cleared cache, tried both nginx and apache. I still have this issue.

**Comment by ahangarha** [comment]
Guys,

I had a guess about CSRF token and came across [this answer](https://stackoverflow.com/a/46141940/5826526) on stackoverflow. I changed the value of `SESSION_DRIVER` in `.env` file to `cookie` and it resolved the issue. Depending on what driver is currently in use, it is highly possible there is a configuration issue with it on server.

My setting was on array since I almost copies `.env.testing`. It doesn't work for sure since it does not persist. Setting it to `file` also didn't work (perhaps for lacking of write access). But `database`, `cookie` and `redis` work fine for me. (I have had installed redis long time ago on my machine. That is why redis works for me)

Please check if this is the reason. It seems my issue is resolved.

**Comment by aleighco** [comment]
Mine has always been set to redis and we have the bad behavior. We still only see it if the end-users manage to get to both http and https, so we just make it all https everywhere and that got rid of the user complaints.

**Comment by ballerburg9005** [comment]
@aleighco: You have a different issue entirely. There are many reasons why you could get a page expired, such as using mixed https and http. However this issue is about people who have configured everything correctly without any sources of error, and who never were able to get it to work even once.

**Comment by ballerburg9005** [comment]
@ahangarha:
> I had a guess about CSRF token and came across [this answer](https://stackoverflow.com/a/46141940/5826526) on stackoverflow. I changed the value of `SESSION_DRIVER` in `.env` file to `cookie` and it resolved the issue. Depending on what driver is currently in use, it is highly possible there is a configuration issue with it on server.

Changing SESSION_DRIVER doesn't work for me. It was one of the first things I tried, as mentioned in the original post.

**Comment by melissaboiko** [comment]
Getting this on fresh new install on debian bullseye, none of the solutions above have worked.

**Comment by melissaboiko** [comment]
I experimentally tried to disable CSRF altogether by editing `app/Http/Middleware/VerifyCsrfToken.php"` and adding an `*` route:

```php
<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        '*', # added this line
        '/api/v1/*'
    ];
}
```

and this fixed it.  So it seems to be some issue with CSRF.  If it helps I'm running nginx, php8.

**Comment by ballerburg9005** [comment]
I have tested it again with latest Git and setting SESSION_DRIVER=cookie does work for me, so that I don't need to disable CSRF as suggested.

Setting this now mysteriously works as well and makes the site function correctly:

```
BROADCAST_DRIVER=redis
CACHE_DRIVER=redis
SESSION_DRIVER=redis
QUEUE_DRIVER=redis
```

To use only HTTP (https will no longer work):
* app/Providers/AppServiceProvider.php : comment out : URL::forceScheme('https')
* config/session.php : set : 'secure' => false
* .env : APP_URL=http://pixelfed.dev
* about:config in Firefox : network.stricttransportsecurity.preloadlist = false (instead change pixelfed.dev to pixelfed.testing everywhere for Chrome-based browsers)

Alternatively set up stunnel or ngix to tunnel through https.

This means that for whatever mysterious reason, the problem disappeared by itself now. I have tested exactly this configuration plus multiple variations of it in the past and it had not worked on my machine. But now it does. I used SESSION_DRIVER=cookie in most of my tests, because this is one of the first things you should be aware to configure, and in the past it changed absolutely nothing. I will leave this issue open for people who still bump into this mystery problem.

**Comment by aungkhantzaw777** [comment]
please change 

SESSION_DRIVER=array to SESSION_DRIVER=file 

@ballerburg9005

**Comment by joergi** [comment]
I'm using Vagrant to start Pixelfed in a VM.

the branch is here:
https://github.com/joergi/pixelfed/tree/vagrant/vagrant

I'm creating a new user, with 
`php artisan user:create` 
I make this the `admin` and I make say ` Manually verify email address? (yes/no) [no]:` NO

So, when logging in, I get the `419 - Page Expired`

I tried both: 
changing
`SESSION_DRIVER=array` to `SESSION_DRIVER=file`
then I get php errors.
so I changed it back
I also changed 
`SESSION_DOMAIN="local.pixelfed.test"` to `SESSION_DOMAIN=""`

(I found this change as solution in some Gihtub issues...)
this is also not working.

Redis is working.... (as this was also an error... in some issues)
